// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.23.3
// source: proto/file.proto

package pb___________

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	PortService_CreateOrUpdatePorts_FullMethodName = "/proto.PortService/CreateOrUpdatePorts"
)

// PortServiceClient is the client API for PortService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PortServiceClient interface {
	CreateOrUpdatePorts(ctx context.Context, opts ...grpc.CallOption) (PortService_CreateOrUpdatePortsClient, error)
}

type portServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPortServiceClient(cc grpc.ClientConnInterface) PortServiceClient {
	return &portServiceClient{cc}
}

func (c *portServiceClient) CreateOrUpdatePorts(ctx context.Context, opts ...grpc.CallOption) (PortService_CreateOrUpdatePortsClient, error) {
	stream, err := c.cc.NewStream(ctx, &PortService_ServiceDesc.Streams[0], PortService_CreateOrUpdatePorts_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &portServiceCreateOrUpdatePortsClient{stream}
	return x, nil
}

type PortService_CreateOrUpdatePortsClient interface {
	Send(*PortRequest) error
	CloseAndRecv() (*PortResponse, error)
	grpc.ClientStream
}

type portServiceCreateOrUpdatePortsClient struct {
	grpc.ClientStream
}

func (x *portServiceCreateOrUpdatePortsClient) Send(m *PortRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *portServiceCreateOrUpdatePortsClient) CloseAndRecv() (*PortResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(PortResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// PortServiceServer is the server API for PortService service.
// All implementations must embed UnimplementedPortServiceServer
// for forward compatibility
type PortServiceServer interface {
	CreateOrUpdatePorts(PortService_CreateOrUpdatePortsServer) error
	mustEmbedUnimplementedPortServiceServer()
}

// UnimplementedPortServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPortServiceServer struct {
}

func (UnimplementedPortServiceServer) CreateOrUpdatePorts(PortService_CreateOrUpdatePortsServer) error {
	return status.Errorf(codes.Unimplemented, "method CreateOrUpdatePorts not implemented")
}
func (UnimplementedPortServiceServer) mustEmbedUnimplementedPortServiceServer() {}

// UnsafePortServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PortServiceServer will
// result in compilation errors.
type UnsafePortServiceServer interface {
	mustEmbedUnimplementedPortServiceServer()
}

func RegisterPortServiceServer(s grpc.ServiceRegistrar, srv PortServiceServer) {
	s.RegisterService(&PortService_ServiceDesc, srv)
}

func _PortService_CreateOrUpdatePorts_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PortServiceServer).CreateOrUpdatePorts(&portServiceCreateOrUpdatePortsServer{stream})
}

type PortService_CreateOrUpdatePortsServer interface {
	SendAndClose(*PortResponse) error
	Recv() (*PortRequest, error)
	grpc.ServerStream
}

type portServiceCreateOrUpdatePortsServer struct {
	grpc.ServerStream
}

func (x *portServiceCreateOrUpdatePortsServer) SendAndClose(m *PortResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *portServiceCreateOrUpdatePortsServer) Recv() (*PortRequest, error) {
	m := new(PortRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// PortService_ServiceDesc is the grpc.ServiceDesc for PortService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PortService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.PortService",
	HandlerType: (*PortServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "CreateOrUpdatePorts",
			Handler:       _PortService_CreateOrUpdatePorts_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "proto/file.proto",
}
